# Generated by Django 4.2.7 on 2025-08-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatModal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_en', models.TextField(blank=True, null=True)),
                ('answer_en', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faq',
            },
        ),
    ]
