# Generated by Django 4.2.7 on 2025-08-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatModal', '0002_faq'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='botresponse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='botresponse',
            name='language',
        ),
        migrations.RemoveField(
            model_name='botresponse',
            name='menu_option',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='menu_context',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='session',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='current_menu',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='language',
        ),
        migrations.AlterUniqueTogether(
            name='menuoption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='menuoption',
            name='language',
        ),
        migrations.RemoveField(
            model_name='menuoption',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='BotResponse',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='MenuOption',
        ),
    ]
