# Generated by Django 4.2.7 on 2025-08-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatModal', '0004_chatsession_language_product_userinput_menuoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
