# Generated by Django 4.2.7 on 2025-08-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatModal', '0006_alter_menuoption_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinput',
            name='session',
        ),
        migrations.AlterUniqueTogether(
            name='menuoption',
            unique_together={('parent', 'language', 'option_number')},
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='UserInput',
        ),
    ]
