# Generated by Django 4.2.7 on 2025-08-05 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatModal', '0007_remove_userinput_session_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuoption',
            unique_together=set(),
        ),
    ]
