# Generated by Django 4.2.7 on 2025-08-05 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatModal', '0009_chatsession_chatlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Please enter a valid 10-digit Indian phone number (no country code or special characters)', regex='^[6-9]\\d{9}$')]),
        ),
    ]
