# Generated by Django 4.2.7 on 2025-08-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatModal', '0010_alter_chatsession_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='botresponse',
            unique_together={('menu_option',)},
        ),
        migrations.RemoveField(
            model_name='botresponse',
            name='language',
        ),
    ]
