# Generated by Django 4.2.7 on 2025-08-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatModal', '0011_alter_botresponse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='is_ai_response',
            field=models.BooleanField(default=False),
        ),
    ]
