# Generated by Django 4.2.7 on 2025-08-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatModal', '0012_chatlog_is_ai_response'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='botresponse',
            unique_together=set(),
        ),
    ]
