# Generated by Django 3.2.25 on 2025-07-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_roles_form_view_roles_report_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='module',
            field=models.TextField(blank=True, null=True),
        ),
    ]
