# Generated by Django 5.0.9 on 2025-08-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_customuser_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual Learner'), ('GROUP_LEADER', 'Group Leader'), ('GROUP_TRAINEE', 'Group Trainee'), ('CORPORATE_TRAINEE', 'Corporate Trainee'), ('CORPORATE_APPROVER', 'Corporate Approver'), ('ADMIN', 'Admin')], default='INDIVIDUAL', max_length=20),
        ),
    ]
