# Generated by Django 5.0.9 on 2025-08-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_customuser_password1_customuser_password2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
