# Generated by Django 4.2.7 on 2025-07-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0084_formfilehist_num_pages_formfiletemp_num_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('index_table', models.TextField(blank=True, null=True)),
                ('file_table', models.TextField(blank=True, null=True)),
                ('data_table', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'module_master',
            },
        ),
        migrations.AddField(
            model_name='form',
            name='module',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='foriegn_key_form_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='is_primary',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
