# Generated by Django 4.2.7 on 2025-07-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0086_invoice_data_formdata_primary_key_invoice_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_action',
            name='primary_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice_data',
            name='primary_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice_file',
            name='primary_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_index',
            name='primary_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
