# Generated by Django 4.2.7 on 2025-07-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0087_invoice_action_primary_key_invoice_data_primary_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulemaster',
            name='action_table',
            field=models.TextField(blank=True, null=True),
        ),
    ]
