# Generated by Django 4.2.7 on 2025-07-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0088_modulemaster_action_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondata',
            name='primary_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfieldvalues',
            name='primary_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formfile',
            name='primary_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='primary_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
