# Generated by Django 4.2.7 on 2025-07-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0089_actiondata_primary_key_formfieldvalues_primary_key_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormData',
            new_name='form_data_master',
        ),
        migrations.RenameModel(
            old_name='FormFieldValues',
            new_name='form_field_values',
        ),
        migrations.RenameModel(
            old_name='FormFile',
            new_name='form_file',
        ),
    ]
