# Generated by Django 4.2.7 on 2025-07-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0090_rename_formdata_form_data_master_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='form_data_master',
            table='form_data_master',
        ),
    ]
