# Generated by Django 4.2.23 on 2025-09-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='statusaction',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statusaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='statusaction',
            name='updated_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='statusaction',
            table='status_action',
        ),
    ]
