# Generated by Django 4.2.23 on 2025-09-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLM', '0002_statusaction_created_at_statusaction_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusaction',
            name='badge_class',
            field=models.CharField(default='bg-secondary', max_length=50),
        ),
    ]
