# Generated by Django 4.2.23 on 2025-09-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLM', '0003_statusaction_badge_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusaction',
            name='action_value',
            field=models.TextField(default=1),
        ),
    ]
