# Generated by Django 4.2.7 on 2025-07-31 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO code or alias (e.g., en, hi, mr)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Display name (e.g., English, Hindi, Marathi)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=100)),
                ('category', models.CharField(choices=[('Pipe Clamps', 'Pipe Clamps'), ('Hydraulic Clamps', 'Hydraulic Clamps'), ('Customized Clamping Systems', 'Customized Clamping Systems')], help_text='Pipe, Hydraulic, Custom', max_length=50)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Rate', max_digits=10, null=True)),
                ('lead_time_days', models.IntegerField(blank=True, help_text='Standard delivery time', null=True)),
                ('spec_link', models.CharField(blank=True, help_text='PDF/URL of specification', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_number', models.CharField(help_text='Display number (e.g., 1, 2a, 3b)', max_length=10)),
                ('menu_text', models.TextField(help_text='Text to display for this menu option')),
                ('response_type', models.CharField(choices=[('menu', 'Menu'), ('response', 'Response')], help_text='menu or response', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='To enable/disable menu options')),
                ('language', models.ForeignKey(help_text='Language for this menu', on_delete=django.db.models.deletion.CASCADE, to='ChatBot.language')),
                ('parent_menu', models.ForeignKey(blank=True, help_text='Refers to parent (null for root)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_options', to='ChatBot.menuoption')),
            ],
            options={
                'ordering': ['parent_menu__id', 'language__id', 'option_number'],
                'unique_together': {('parent_menu', 'language', 'option_number')},
            },
        ),
        migrations.CreateModel(
            name='BotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(help_text='Bot’s reply in English (will be translated)')),
                ('media_url', models.CharField(blank=True, help_text='URL if media/file attached (optional)', max_length=255, null=True)),
                ('language', models.ForeignKey(help_text='Language for this response', on_delete=django.db.models.deletion.CASCADE, to='ChatBot.language')),
                ('menu_option', models.ForeignKey(blank=True, help_text='Links to menu item (optional if response is standalone)', null=True, on_delete=django.db.models.deletion.CASCADE, to='ChatBot.menuoption')),
            ],
        ),
    ]
