# Generated by Django 4.2.7 on 2025-07-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botresponse',
            name='language',
        ),
        migrations.RemoveField(
            model_name='botresponse',
            name='menu_option',
        ),
        migrations.AlterUniqueTogether(
            name='menuoption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='menuoption',
            name='language',
        ),
        migrations.RemoveField(
            model_name='menuoption',
            name='parent_menu',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='BotResponse',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='MenuOption',
        ),
    ]
