# Generated by Django 4.2.7 on 2025-07-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ChatBot', '0002_remove_botresponse_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_en', models.TextField(blank=True, null=True)),
                ('answer_en', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faq',
            },
        ),
    ]
