# Generated by Django 4.2.7 on 2025-08-01 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO language code (e.g., en, hi, mr)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Display name of the language', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this language is available')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('category', models.CharField(choices=[('pipe', 'Pipe Clamps'), ('hydraulic', 'Hydraulic Clamps'), ('custom', 'Customized Clamping Systems')], help_text='Product category', max_length=20)),
                ('code', models.CharField(help_text='Product code/SKU', max_length=50, unique=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='Standard delivery time in days')),
                ('spec_link', models.URLField(blank=True, help_text='URL to product specifications', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this product is available')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('is_menu_selection', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='ChatBot.chatsession')),
            ],
            options={
                'verbose_name': 'User Input',
                'verbose_name_plural': 'User Inputs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_number', models.CharField(help_text='Display number (e.g., 1, 2a, 3b)', max_length=10)),
                ('menu_text', models.TextField(help_text='Text to display for this menu option')),
                ('response_type', models.CharField(choices=[('menu', 'Menu'), ('response', 'Response'), ('input', 'Requires Input')], default='menu', help_text='Type of response expected', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this menu option is available')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering of menu items')),
                ('language', models.ForeignKey(help_text='Language for this menu option', on_delete=django.db.models.deletion.CASCADE, to='ChatBot.language')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu item, null for root items', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ChatBot.menuoption')),
            ],
            options={
                'verbose_name': 'Menu Option',
                'verbose_name_plural': 'Menu Options',
                'ordering': ['order', 'option_number'],
                'unique_together': {('parent', 'language', 'option_number')},
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='current_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChatBot.menuoption'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChatBot.language'),
        ),
        migrations.CreateModel(
            name='BotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(help_text="Bot's reply text")),
                ('media_url', models.URLField(blank=True, help_text='URL to media file if attached', max_length=500, null=True)),
                ('language', models.ForeignKey(help_text='Language for this response', on_delete=django.db.models.deletion.CASCADE, to='ChatBot.language')),
                ('menu_option', models.ForeignKey(help_text='Linked menu option', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ChatBot.menuoption')),
            ],
            options={
                'verbose_name': 'Bot Response',
                'verbose_name_plural': 'Bot Responses',
                'unique_together': {('menu_option', 'language')},
            },
        ),
    ]
