# Generated by Django 4.2.7 on 2025-08-01 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0004_chatsession_language_product_userinput_menuoption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botresponse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={},
        ),
        migrations.AlterModelOptions(
            name='menuoption',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='botresponse',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='menuoption',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='botresponse',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ChatBot.language'),
        ),
        migrations.AlterField(
            model_name='botresponse',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='botresponse',
            name='menu_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBot.menuoption'),
        ),
        migrations.AlterField(
            model_name='botresponse',
            name='response_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='menuoption',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuoption',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ChatBot.language'),
        ),
        migrations.AlterField(
            model_name='menuoption',
            name='menu_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menuoption',
            name='option_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='menuoption',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuoption',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ChatBot.menuoption'),
        ),
        migrations.AlterField(
            model_name='menuoption',
            name='response_type',
            field=models.CharField(choices=[('menu', 'Menu'), ('response', 'Response')], max_length=20),
        ),
    ]
