# Generated by Django 4.2.7 on 2025-08-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0005_alter_botresponse_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botresponse',
            name='language',
        ),
        migrations.RemoveField(
            model_name='botresponse',
            name='menu_option',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='current_menu',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='language',
        ),
        migrations.RemoveField(
            model_name='menuoption',
            name='language',
        ),
        migrations.RemoveField(
            model_name='menuoption',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='userinput',
            name='session',
        ),
        migrations.DeleteModel(
            name='BotResponse',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='MenuOption',
        ),
        migrations.DeleteModel(
            name='UserInput',
        ),
    ]
