# Generated by Django 4.2.7 on 2025-08-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBot', '0006_remove_botresponse_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO language code (e.g., en, hi, mr)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Display name of the language', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('pipe', 'Pipe Clamps'), ('hydraulic', 'Hydraulic Clamps'), ('custom', 'Customized Clamping Systems')], max_length=100)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lead_time_days', models.PositiveIntegerField(help_text='Standard delivery time in days')),
                ('spec_link', models.URLField(blank=True, help_text='URL for product specifications', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_number', models.CharField(help_text='Display number (e.g., 1, 2a, 3b)', max_length=10)),
                ('menu_text', models.TextField(help_text='Text to display for this menu option')),
                ('response_type', models.CharField(choices=[('menu', 'Menu'), ('response', 'Response'), ('input', 'User Input Required')], default='menu', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_user_input', models.BooleanField(default=False, help_text='Does this option require user input?')),
                ('input_prompt', models.TextField(blank=True, help_text='Prompt to show when input is required', null=True)),
                ('language', models.ForeignKey(help_text='Language for this menu option', on_delete=django.db.models.deletion.CASCADE, to='ChatBot.language')),
                ('parent_menu', models.ForeignKey(blank=True, help_text='Parent menu item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ChatBot.menuoption')),
            ],
            options={
                'verbose_name': 'Menu Option',
                'verbose_name_plural': 'Menu Options',
                'ordering': ['option_number'],
                'unique_together': {('parent_menu', 'language', 'option_number')},
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_data', models.JSONField(blank=True, default=dict, help_text='Stores temporary user data during session')),
                ('current_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChatBot.language')),
                ('current_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChatBot.menuoption')),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('is_user', models.BooleanField(default=False, help_text='Is this message from the user?')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('menu_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChatBot.menuoption')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ChatBot.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BotResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(help_text="Bot's reply text")),
                ('media_url', models.URLField(blank=True, help_text='URL for attached media/file', null=True)),
                ('additional_actions', models.JSONField(blank=True, help_text='Additional actions or metadata', null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatBot.language')),
                ('menu_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ChatBot.menuoption')),
            ],
            options={
                'verbose_name': 'Bot Response',
                'verbose_name_plural': 'Bot Responses',
            },
        ),
    ]
