# Generated by Django 5.0.9 on 2025-08-05 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'checklist_types',
            },
        ),
        migrations.CreateModel(
            name='ChecklistDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PDF', 'PDF Document'), ('DOC', 'Word Document (.docx)'), ('XLS', 'Excel Spreadsheet'), ('PPT', 'PowerPoint Presentation')], max_length=10)),
                ('file', models.FileField(upload_to='compliance_docs/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('checklist_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Checklist.checklisttype')),
            ],
            options={
                'db_table': 'checklist_documents',
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('risk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='Checklist.checklisttype')),
            ],
            options={
                'db_table': 'checklists',
            },
        ),
    ]
