# Generated by Django 5.0.9 on 2025-08-06 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_type', models.CharField(max_length=100)),
                ('doc_type', models.CharField(choices=[('PDF', 'Reference Document (PDF)'), ('DOC', 'Declaration Form (Word .docx)')], max_length=3)),
                ('file', models.FileField(upload_to='compliance_docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Checklist Document',
                'verbose_name_plural': 'Checklist Documents',
                'ordering': ['checklist_type', 'doc_type'],
            },
        ),
        migrations.AlterField(
            model_name='checklist',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='task',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='checklist',
            table='checklist',
        ),
        migrations.DeleteModel(
            name='ChecklistDoc',
        ),
        migrations.DeleteModel(
            name='ChecklistType',
        ),
    ]
