# Generated by Django 5.0.9 on 2025-08-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checklist', '0002_checklistdocument_alter_checklist_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistdocument',
            options={},
        ),
        migrations.AlterModelTable(
            name='checklistdocument',
            table='checklist_doc',
        ),
    ]
