# Generated by Django 5.0.9 on 2025-08-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checklist', '0003_alter_checklistdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Compliant', 'Compliant'), ('Not Compliant', 'Not Compliant'), ('Compliant But Delayed', 'Compliant But Delayed'), ('Rejected', 'Rejected'), ('Not Applicable', 'Not Applicable'), ('Partially Compliant', 'Partially Compliant'), ('Escalated', 'Escalated'), ('Closed', 'Closed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
