# Generated by Django 4.2.7 on 2025-08-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBIDashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='TWX Dashboard', max_length=100, unique=True)),
                ('tenant_id', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('workspace_id', models.CharField(max_length=255)),
                ('report_id', models.CharField(max_length=255)),
                ('report_id_2', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
