# Generated by Django 4.2.7 on 2025-07-30 06:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MachinePlan', '0006_machine_work_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=10, unique=True, verbose_name='Employee ID')),
                ('employee_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Hire Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Employee')),
                ('contact_number', models.CharField(blank=True, max_length=15, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MachinePlan.workcenter', verbose_name='Primary Work Center')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employee_name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_code', models.CharField(max_length=10, unique=True, verbose_name='Shift Code')),
                ('shift_name', models.CharField(max_length=50, verbose_name='Shift Name')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Shift')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_code', models.CharField(max_length=10, unique=True, verbose_name='Skill Code')),
                ('skill_name', models.CharField(max_length=50, verbose_name='Skill Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['skill_name'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('personal', 'Personal Leave'), ('bereavement', 'Bereavement Leave'), ('other', 'Other')], max_length=20, verbose_name='Leave Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('reason', models.TextField(verbose_name='Reason for Leave')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('notes', models.TextField(blank=True, verbose_name='Approver Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to='Manpower.employee', verbose_name='Approved By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='Manpower.employee')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LaborRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees_needed', models.PositiveSmallIntegerField(default=1, verbose_name='Employees Needed')),
                ('min_proficiency', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Minimum Proficiency')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_requirements', to='MachinePlan.routing')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Manpower.skill', verbose_name='Required Skill')),
            ],
            options={
                'verbose_name': 'Labor Requirement',
                'verbose_name_plural': 'Labor Requirements',
                'unique_together': {('routing', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='LaborAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Assignment Date')),
                ('hours_allocated', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(24)], verbose_name='Hours Allocated')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('absent', 'Absent'), ('reassigned', 'Reassigned')], default='planned', max_length=20, verbose_name='Assignment Status')),
                ('notes', models.TextField(blank=True, verbose_name='Assignment Notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Manpower.employee', verbose_name='Assigned Employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_assignments', to='MachinePlan.machineschedule')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Manpower.shift', verbose_name='Assigned Shift')),
            ],
            options={
                'verbose_name': 'Labor Assignment',
                'verbose_name_plural': 'Labor Assignments',
                'ordering': ['date', 'shift__start_time'],
                'unique_together': {('employee', 'date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.PositiveSmallIntegerField(choices=[(1, 'Basic Knowledge'), (2, 'Novice'), (3, 'Competent'), (4, 'Proficient'), (5, 'Expert')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('certification_date', models.DateField(blank=True, null=True, verbose_name='Certification Date')),
                ('certified_by', models.CharField(blank=True, max_length=100, verbose_name='Certified By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='Manpower.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manpower.skill')),
            ],
            options={
                'verbose_name': 'Employee Skill',
                'verbose_name_plural': 'Employee Skills',
                'unique_together': {('employee', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Reason for Unavailability')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='Manpower.employee')),
            ],
            options={
                'verbose_name': 'Employee Availability',
                'verbose_name_plural': 'Employee Availabilities',
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('clock_in', models.DateTimeField(blank=True, null=True, verbose_name='Clock In Time')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='Clock Out Time')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late Arrival'), ('left_early', 'Left Early'), ('on_leave', 'On Leave')], default='present', max_length=20, verbose_name='Attendance Status')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Overtime Hours')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Manpower.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Manpower.shift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
