# Generated by Django 4.2.7 on 2025-07-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0010_remove_machineschedule_component_and_more'),
        ('Manpower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborassignment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_assignments', to='MachinePlan.machineplanning'),
        ),
    ]
