# Generated by Django 4.2.7 on 2025-07-31 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0002_alter_laborassignment_schedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laborassignment',
            unique_together=set(),
        ),
    ]
