# Generated by Django 4.2.7 on 2025-08-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0003_alter_laborassignment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='is_active',
        ),
    ]
