# Generated by Django 4.2.23 on 2025-08-19 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0004_remove_employee_is_active_remove_shift_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_assignments', to='Manpower.employee', verbose_name='Assigned Employee'),
        ),
    ]
