# Generated by Django 4.2.23 on 2025-08-20 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0006_employee_is_active_shift_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborrequirement',
            name='min_proficiency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Beginner (Basic knowledge)'), (2, 'Novice (Limited experience)'), (3, 'Competent (Practical application)'), (4, 'Professional (Thorough understanding)'), (5, 'Expert (Advanced mastery)')], default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Minimum Proficiency'),
        ),
    ]
