# Generated by Django 4.2.23 on 2025-08-21 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0007_alter_laborrequirement_min_proficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proficeincy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Proficiency Name')),
                ('is_active', models.BooleanField(blank=True, verbose_name='active')),
            ],
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='proficiency',
            field=models.ForeignKey(blank=True, db_column='proficiency_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_proficiency', to='Manpower.proficeincy'),
        ),
        migrations.AlterField(
            model_name='laborrequirement',
            name='min_proficiency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='require_proficiency', to='Manpower.proficeincy'),
        ),
    ]
