# Generated by Django 4.2.23 on 2025-08-21 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0023_machinescheduling'),
        ('Manpower', '0008_proficeincy_alter_employeeskill_proficiency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborassignment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_assignments', to='MachinePlan.machinescheduling'),
        ),
    ]
