# Generated by Django 4.2.23 on 2025-08-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0023_machinescheduling'),
        ('Manpower', '0009_alter_laborassignment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborrequirement',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MachinePlan.machinescheduling'),
        ),
    ]
