# Generated by Django 4.2.23 on 2025-08-28 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0024_alter_machine_machine_type_and_more'),
        ('Manpower', '0010_laborrequirement_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manpower.shift', verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.workcenter', verbose_name='Primary Work Center'),
        ),
        migrations.AlterField(
            model_name='laborassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_assignments', to='Manpower.employee', verbose_name='Assigned Employee'),
        ),
        migrations.AlterField(
            model_name='laborassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manpower.shift', verbose_name='Assigned Shift'),
        ),
        migrations.AlterField(
            model_name='laborrequirement',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.machinescheduling'),
        ),
        migrations.AlterField(
            model_name='laborrequirement',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manpower.skill', verbose_name='Required Skill'),
        ),
    ]
