# Generated by Django 4.2.23 on 2025-09-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0011_alter_attendance_shift_alter_employee_work_center_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laborassignment',
            options={'ordering': ['start_date', 'shift__start_time'], 'verbose_name': 'Labor Assignment', 'verbose_name_plural': 'Labor Assignments'},
        ),
        migrations.RemoveField(
            model_name='laborassignment',
            name='date',
        ),
        migrations.AddField(
            model_name='laborassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Assignment Date'),
        ),
        migrations.AddField(
            model_name='laborassignment',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Assignment Date'),
        ),
    ]
