# Generated by Django 5.0.9 on 2025-10-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpdprogram',
            name='co_organizers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
