# Generated by Django 4.2.23 on 2025-10-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManpowerPlan', '0001_initial'),
        ('MachinePlanning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinescheduledetail',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ManpowerPlan.shift'),
        ),
        migrations.AddField(
            model_name='routing',
            name='min_proficiency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rou_require_proficiency', to='ManpowerPlan.proficeincy'),
        ),
        migrations.AddField(
            model_name='routing',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ManpowerPlan.skill', verbose_name='rou_Required Skill'),
        ),
        migrations.AddField(
            model_name='routingdetail',
            name='min_proficiency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rout_require_proficiency', to='ManpowerPlan.proficeincy'),
        ),
        migrations.AddField(
            model_name='routingdetail',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ManpowerPlan.skill', verbose_name='Required Skill'),
        ),
    ]
