# Generated by Django 4.2.23 on 2025-10-06 11:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManpowerPlan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MachinePlanning', '0002_machinescheduledetail_shift_routing_min_proficiency_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkCenter',
            new_name='WorkCenters',
        ),
    ]
