# Generated by Django 4.2.23 on 2025-10-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0004_workstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
