# Generated by Django 4.2.23 on 2025-10-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0005_workstation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcenters',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstation_id', to='MachinePlanning.workstation', verbose_name='Work Station'),
        ),
    ]
