# Generated by Django 4.2.23 on 2025-10-07 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0006_workcenters_workstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinescheduledetail',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MachinePlanning.workstation'),
        ),
    ]
