# Generated by Django 4.2.23 on 2025-10-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0007_machinescheduledetail_workstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingdetail',
            name='routing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='MachinePlanning.routing'),
        ),
        migrations.DeleteModel(
            name='RoutingMaster',
        ),
    ]
