# Generated by Django 4.2.23 on 2025-10-07 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0018_remove_componentsupplier_price_bomitem_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MachinePlanning', '0008_alter_routingdetail_routing_delete_routingmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.bomheader', verbose_name='BOM Component')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routingmaster_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routingmaster_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'BOM Routing',
                'verbose_name_plural': 'BOM Routings',
            },
        ),
        migrations.AlterField(
            model_name='routingdetail',
            name='routing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='MachinePlanning.routingmaster'),
        ),
    ]
