# Generated by Django 4.2.23 on 2025-10-07 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0018_remove_componentsupplier_price_bomitem_price'),
        ('MachinePlanning', '0009_routingmaster_alter_routingdetail_routing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routing',
            options={'verbose_name': 'BOM Routing', 'verbose_name_plural': 'BOM Routings'},
        ),
        migrations.AlterUniqueTogether(
            name='routing',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='routing',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_route', to='BOM.bomheader', verbose_name='BOM Component'),
        ),
        migrations.RemoveField(
            model_name='routing',
            name='employees_needed',
        ),
        migrations.RemoveField(
            model_name='routing',
            name='min_proficiency',
        ),
        migrations.RemoveField(
            model_name='routing',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='routing',
            name='production_order',
        ),
        migrations.RemoveField(
            model_name='routing',
            name='run_time_per_unit',
        ),
        migrations.RemoveField(
            model_name='routing',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='routing',
            name='setup_time',
        ),
        migrations.RemoveField(
            model_name='routing',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='routing',
            name='work_center',
        ),
    ]
