# Generated by Django 4.2.23 on 2025-10-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0010_alter_routing_options_alter_routing_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routing',
            name='component',
        ),
        migrations.RemoveField(
            model_name='routing',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='routing',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='machineplanning',
            name='routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MachinePlanning.routingmaster'),
        ),
        migrations.AlterField(
            model_name='machineschedule',
            name='routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MachinePlanning.routingmaster'),
        ),
        migrations.AlterField(
            model_name='machinescheduledetail',
            name='routing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachinePlanning.routingmaster'),
        ),
        migrations.AlterField(
            model_name='machinescheduling',
            name='routing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachinePlanning.routingmaster'),
        ),
    ]
