# Generated by Django 4.2.23 on 2025-10-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManpowerPlan', '0002_alter_laborrequirement_routing'),
        ('MachinePlanning', '0011_remove_routing_component_remove_routing_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Routing',
        ),
    ]
