# Generated by Django 4.2.23 on 2025-10-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0012_delete_routing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineschedule',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Schedule Name'),
        ),
    ]
