# Generated by Django 4.2.23 on 2025-10-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0013_alter_machineschedule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineschedule',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Schedule Name'),
        ),
    ]
