# Generated by Django 4.2.23 on 2025-10-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0014_alter_machineschedule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='employee_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
