# Generated by Django 4.2.23 on 2025-10-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0015_workstation_employee_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinescheduledetail',
            name='workstation',
        ),
        migrations.RemoveField(
            model_name='workcenters',
            name='workstation',
        ),
        migrations.DeleteModel(
            name='WorkStation',
        ),
    ]
