# Generated by Django 4.2.23 on 2025-10-08 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MachinePlanning', '0016_remove_machinescheduledetail_workstation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('employee', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstations_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstation', to='MachinePlanning.machine', verbose_name='Machine')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstations_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Work Station',
                'verbose_name_plural': 'Work Stations',
                'ordering': ['machine__machine_id'],
            },
        ),
    ]
