# Generated by Django 4.2.23 on 2025-10-08 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0017_workstations'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinescheduledetail',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MachinePlanning.workstations'),
        ),
        migrations.AddField(
            model_name='workcenters',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workstation_id', to='MachinePlanning.workstations', verbose_name='Work Station'),
        ),
    ]
