# Generated by Django 4.2.23 on 2025-10-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0018_machinescheduledetail_workstation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstations',
            name='employee',
            field=models.TextField(blank=True, null=True, verbose_name='Assigned Employees'),
        ),
    ]
