# Generated by Django 4.2.23 on 2025-10-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0019_alter_workstations_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinescheduledetail',
            options={'ordering': ['seq'], 'verbose_name': 'Machine Schedule Detail'},
        ),
        migrations.RemoveField(
            model_name='machinescheduledetail',
            name='actual_end',
        ),
        migrations.RemoveField(
            model_name='machinescheduledetail',
            name='actual_start',
        ),
        migrations.RemoveField(
            model_name='machinescheduledetail',
            name='scheduled_end',
        ),
        migrations.RemoveField(
            model_name='machinescheduledetail',
            name='scheduled_start',
        ),
    ]
