# Generated by Django 4.2.23 on 2025-10-08 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0020_alter_machinescheduledetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstations',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_center_station', to='MachinePlanning.workcenters'),
        ),
    ]
