# Generated by Django 4.2.23 on 2025-10-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0021_workstations_work_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workcenters',
            name='workstation',
        ),
    ]
