# Generated by Django 4.2.23 on 2025-10-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0022_remove_workcenters_workstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcenters',
            name='workstation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
