# Generated by Django 4.2.23 on 2025-10-09 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0023_workcenters_workstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='work_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_workstation', to='MachinePlanning.workstations'),
        ),
    ]
