# Generated by Django 4.2.23 on 2025-10-09 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0024_machine_work_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='work_station',
        ),
    ]
