# Generated by Django 4.2.23 on 2025-10-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0025_remove_machine_work_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workcenters',
            name='workstation',
        ),
        migrations.AddField(
            model_name='workcenters',
            name='workstation_ids',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
