# Generated by Django 4.2.23 on 2025-10-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0026_remove_workcenters_workstation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstations',
            name='work_center',
        ),
    ]
