# Generated by Django 4.2.23 on 2025-10-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0027_remove_workstations_work_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machineschedule',
            old_name='ccreated_at',
            new_name='created_at',
        ),
    ]
