# Generated by Django 4.2.23 on 2025-10-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0028_rename_ccreated_at_machineschedule_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workstations',
            options={'verbose_name': 'Work Station', 'verbose_name_plural': 'Work Stations'},
        ),
        migrations.AlterField(
            model_name='workstations',
            name='employee',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Assigned Employees'),
        ),
        migrations.AlterField(
            model_name='workstations',
            name='machine',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
