# Generated by Django 4.2.23 on 2025-10-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0029_alter_workstations_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstations',
            name='employee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assigned Employees'),
        ),
        migrations.AlterField(
            model_name='workstations',
            name='machine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
