# Generated by Django 4.2.23 on 2025-10-17 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MachinePlanning', '0031_holiday_weeklyoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('workstation', models.CharField(max_length=255)),
                ('machine', models.CharField(max_length=255)),
                ('employees', models.TextField(help_text='Comma-separated employee IDs')),
                ('shift', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_quantity', models.IntegerField(default=0)),
                ('completed_quantity', models.IntegerField(default=0)),
                ('remaining_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shift_tables', to=settings.AUTH_USER_MODEL)),
                ('machine_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_tables', to='MachinePlanning.machineschedule')),
                ('machine_schedule_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_tables', to='MachinePlanning.machinescheduledetail')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shift_tables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
