# Generated by Django 4.2.23 on 2025-10-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0032_shifttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttable',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shifttable',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
