# Generated by Django 4.2.23 on 2025-10-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0033_alter_shifttable_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttable',
            name='machine',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shifttable',
            name='workstation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstionn', to='MachinePlanning.workstations'),
        ),
    ]
