# Generated by Django 4.2.23 on 2025-10-17 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0018_remove_componentsupplier_price_bomitem_price'),
        ('MaterialPlan', '0004_productionorder_order_status'),
        ('ManpowerPlan', '0008_alter_shift_break_time_period'),
        ('MachinePlanning', '0034_alter_shifttable_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttable',
            name='bom_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_shift', to='BOM.bomheader'),
        ),
        migrations.AddField(
            model_name='shifttable',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_order', to='MaterialPlan.productionorder'),
        ),
        migrations.AddField(
            model_name='shifttable',
            name='week',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shifttable',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_shift', to='ManpowerPlan.shift'),
        ),
    ]
