# Generated by Django 4.2.23 on 2025-10-27 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0035_shifttable_bom_component_shifttable_production_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingdetail',
            name='routing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_details', to='MachinePlanning.routingmaster'),
        ),
    ]
