# Generated by Django 4.2.23 on 2025-10-29 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MaterialPlan', '0004_productionorder_order_status'),
        ('MachinePlanning', '0036_alter_routingdetail_routing'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.TextField()),
                ('quanity', models.IntegerField(max_length=10)),
                ('production_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PLANNED', 'Planned')], default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batch', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_production_order', to='MaterialPlan.productionorder')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_batch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchRoutingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('employee', models.CharField(max_length=100)),
                ('quantity_pass', models.IntegerField()),
                ('quantity_reject', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_routing_no', to='MachinePlanning.batchmaster')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batch_routing_tables', to=settings.AUTH_USER_MODEL)),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_machine', to='MachinePlanning.machine')),
                ('machine_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_schedule_id', to='MachinePlanning.machineschedule')),
                ('machine_schedule_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_schedule_detail_id', to='MachinePlanning.machinescheduledetail')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_batch_routing_tables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
