# Generated by Django 4.2.23 on 2025-10-30 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0018_remove_componentsupplier_price_bomitem_price'),
        ('MachinePlanning', '0037_batchmaster_batchroutinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchmaster',
            name='bom_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_batch_component', to='BOM.bomheader'),
        ),
        migrations.AddField(
            model_name='batchmaster',
            name='machine_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_master_schedule', to='MachinePlanning.machineschedule'),
        ),
        migrations.AlterField(
            model_name='batchmaster',
            name='quanity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='batchroutinglog',
            name='machine_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_schedule_id', to='MachinePlanning.machineschedule'),
        ),
    ]
