# Generated by Django 4.2.23 on 2025-10-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0038_batchmaster_bom_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinescheduledetail',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_detail_operation', to='MachinePlanning.operation'),
        ),
    ]
