# Generated by Django 4.2.23 on 2025-10-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0039_machinescheduledetail_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchroutinglog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchroutinglog',
            name='quantity_pass',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchroutinglog',
            name='quantity_reject',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchroutinglog',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
