# Generated by Django 4.2.23 on 2025-10-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0040_alter_batchroutinglog_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchroutinglog',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
    ]
