# Generated by Django 4.2.23 on 2025-10-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0041_batchroutinglog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchroutinglog',
            name='status',
        ),
    ]
