# Generated by Django 4.2.23 on 2025-11-03 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0019_bomheader_wastage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MachinePlanning', '0042_remove_batchroutinglog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity', models.CharField(blank=True, max_length=255, null=True)),
                ('packaging', models.CharField(blank=True, max_length=255, null=True)),
                ('other_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_costs', to='BOM.bomheader')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additionalcosts_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additionalcosts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Additional Cost',
                'verbose_name_plural': 'Additional Costs',
                'db_table': 'sc_additional_cost',
            },
        ),
    ]
