# Generated by Django 4.2.23 on 2025-11-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0043_additionalcost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalcost',
            old_name='other_cost',
            new_name='consumables',
        ),
        migrations.AddField(
            model_name='additionalcost',
            name='depreciation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='additionalcost',
            name='maintenance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='additionalcost',
            name='overhead',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='additionalcost',
            name='wastage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='additionalcost',
            table='cost_element',
        ),
    ]
