# Generated by Django 4.2.23 on 2025-11-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0044_rename_other_cost_additionalcost_consumables_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalCost',
        ),
    ]
