# Generated by Django 4.2.23 on 2025-11-03 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BOM', '0019_bomheader_wastage'),
        ('MachinePlanning', '0045_delete_additionalcost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('bom_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_cost_values', to='BOM.bomheader')),
            ],
            options={
                'verbose_name': 'Cost Element',
                'verbose_name_plural': 'Cost Element',
                'db_table': 'cost_element',
            },
        ),
        migrations.CreateModel(
            name='CostElementValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_values', to='MachinePlanning.costelement')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_values_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_values_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cost Element Value',
                'verbose_name_plural': 'Cost Element Values',
                'db_table': 'cost_element_value',
            },
        ),
    ]
