# Generated by Django 4.2.23 on 2025-11-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0046_costelement_costelementvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='cost_per_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
