# Generated by Django 4.2.23 on 2025-11-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0048_machinecapabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinecapabilities',
            name='unit_of_measure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
