# Generated by Django 4.2.23 on 2025-11-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0049_machinecapabilities_unit_of_measure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='cost_per_unit',
            new_name='cost_per_hour',
        ),
    ]
