# Generated by Django 4.2.23 on 2025-11-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0050_rename_cost_per_unit_operation_cost_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingdetail',
            name='emplpyee_cost',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routingdetail',
            name='machine_cost',
            field=models.TextField(blank=True, null=True),
        ),
    ]
