# Generated by Django 4.2.23 on 2025-11-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0052_cogmaster_cogdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingdetail',
            name='emplpyee_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='routingdetail',
            name='machine_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
