# Generated by Django 4.2.23 on 2025-11-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0053_alter_routingdetail_emplpyee_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routingdetail',
            name='production_order',
        ),
        migrations.RemoveField(
            model_name='routingdetail',
            name='run_time_per_unit',
        ),
        migrations.RemoveField(
            model_name='routingdetail',
            name='setup_time',
        ),
    ]
