# Generated by Django 4.2.23 on 2025-11-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0054_remove_routingdetail_production_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='consumables_cost',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='depriciation_cost',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='electricity_cost',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='maintenance_cost',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
