# Generated by Django 4.2.23 on 2025-11-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0055_machine_consumables_cost_machine_depriciation_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='consumables_cost',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='depriciation_cost',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='electricity_cost',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='maintenance_cost',
        ),
    ]
