# Generated by Django 4.2.23 on 2025-11-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0056_remove_machine_consumables_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routingdetail',
            old_name='emplpyee_cost',
            new_name='employee_cost',
        ),
    ]
