# Generated by Django 4.2.23 on 2025-11-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0057_rename_emplpyee_cost_routingdetail_employee_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routingdetail',
            old_name='employee_cost',
            new_name='employee_capacity',
        ),
        migrations.RenameField(
            model_name='routingdetail',
            old_name='machine_cost',
            new_name='machine_capacity',
        ),
    ]
