# Generated by Django 4.2.23 on 2025-11-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0059_alter_routingdetail_employee_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingdetail',
            name='employee_capacity',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='routingdetail',
            name='machine_capacity',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
