# Generated by Django 4.2.23 on 2025-11-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0062_alter_routingdetail_employee_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cogmaster',
            name='bom_header',
        ),
        migrations.RemoveField(
            model_name='cogmaster',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cogmaster',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='costelement',
            name='bom_header',
        ),
        migrations.RemoveField(
            model_name='costelementvalue',
            name='cost_key',
        ),
        migrations.RemoveField(
            model_name='costelementvalue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='costelementvalue',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='COGDetail',
        ),
        migrations.DeleteModel(
            name='COGMaster',
        ),
        migrations.DeleteModel(
            name='CostElement',
        ),
        migrations.DeleteModel(
            name='CostElementValue',
        ),
    ]
