# Generated by Django 4.2.23 on 2025-11-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0063_remove_cogmaster_bom_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttable',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_shift', to='MachinePlanning.machine'),
        ),
    ]
