# Generated by Django 5.0.9 on 2025-07-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0002_alter_approvalrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomitem',
            options={},
        ),
        migrations.AddField(
            model_name='bomitem',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='component',
            name='purchase_type',
            field=models.CharField(choices=[('IN', 'Inhouse'), ('PU', 'Purchase'), ('OS', 'Outsource')], default='PU', max_length=2),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='sort_order',
            field=models.CharField(max_length=20),
        ),
    ]
