# Generated by Django 5.0.9 on 2025-07-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0003_alter_bomitem_options_bomitem_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
