# Generated by Django 5.0.9 on 2025-07-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0004_bomitem_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Plastic', 'Plastic'), ('Metal', 'Metal'), ('Chemical', 'Chemical'), ('Other', 'Other')], default='Mechanical', max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='purchase_type',
            field=models.CharField(choices=[('Inhouse', 'Inhouse'), ('Purchase', 'Purchase'), ('Outsource', 'Outsource')], default='Purchase', max_length=100),
        ),
    ]
