# Generated by Django 5.0.9 on 2025-07-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0005_alter_component_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomheader',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('AC', 'Active'), ('OB', 'Obsolete'), ('PE', 'Pending Approval'), ('PE', 'Pending Approval')], default='Draft', max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.CharField(choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Electronic', 'Electronic'), ('Sealing', 'Sealing'), ('Plastic', 'Plastic'), ('Metal', 'Metal'), ('Chemical', 'Chemical'), ('Structural', 'Structural'), ('Electro-Mechanical', 'Electro-Mechanical'), ('Other', 'Other')], default='Mechanical', max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='purchase_type',
            field=models.CharField(choices=[('Inhouse', 'Inhouse'), ('Purchase', 'Purchase'), ('Outsource', 'Outsource'), ('Manufactured', 'Manufactured')], default='Purchase', max_length=100),
        ),
    ]
