# Generated by Django 5.0.9 on 2025-07-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0006_alter_bomheader_status_alter_component_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomheader',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Obsolete', 'Obsolete'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved')], default='Draft', max_length=100),
        ),
    ]
