# Generated by Django 5.0.9 on 2025-07-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0007_alter_bomheader_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Datasheet', 'Datasheet'), ('Drawing', 'Drawing'), ('Instruction', 'Instruction'), ('Certificate', 'Certificate'), ('Other', 'Other')], default='Datasheet', max_length=100),
        ),
    ]
