# Generated by Django 4.2.7 on 2025-07-31 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0008_alter_document_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_on_hand', models.PositiveIntegerField()),
                ('quantity_allocated', models.PositiveIntegerField()),
                ('available_quantity', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_history', to='BOM.component')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BOM.inventorylocation')),
            ],
            options={
                'ordering': ['component', 'snapshot_date'],
                'unique_together': {('component', 'location', 'snapshot_date')},
            },
        ),
    ]
