# Generated by Django 4.2.7 on 2025-08-01 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialPlan', '0002_alter_inventoryreservation_id_alter_materialplan_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BOM', '0009_inventoryhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_receipt_date', models.DateTimeField()),
                ('quantity_received', models.DecimalField(decimal_places=3, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Accepted By')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MaterialPlan.purchaserequisition', verbose_name='Requisition')),
            ],
            options={
                'verbose_name_plural': 'Purchase Receipts',
            },
        ),
        migrations.CreateModel(
            name='ComponentCostParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering_cost', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('holding_cost_pct', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BOM.component')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('adjustment', 'Adjustment')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(max_length=100)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BOM.component')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BOM.inventorylocation')),
            ],
            options={
                'indexes': [models.Index(fields=['component', 'date'], name='BOM_invento_compone_1afde5_idx')],
            },
        ),
    ]
