# Generated by Django 4.2.7 on 2025-08-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0010_purchasereceipt_componentcostparameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyComponentDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_issued', models.DecimalField(decimal_places=3, max_digits=12)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.component')),
            ],
            options={
                'ordering': ['component', 'month'],
                'unique_together': {('component', 'month')},
            },
        ),
    ]
