# Generated by Django 4.2.7 on 2025-08-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0011_monthlycomponentdemand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlycomponentdemand',
            options={},
        ),
        migrations.AlterField(
            model_name='monthlycomponentdemand',
            name='component',
            field=models.ForeignKey(db_column='component_id', on_delete=django.db.models.deletion.CASCADE, to='BOM.component', to_field='part_number'),
        ),
        migrations.AlterField(
            model_name='monthlycomponentdemand',
            name='total_issued',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='monthlycomponentdemand',
            table='BOM_monthlycomponentdemand',
        ),
    ]
