# Generated by Django 4.2.23 on 2025-08-25 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BOM', '0012_alter_monthlycomponentdemand_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conducted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('adjusted', 'Adjusted')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_stocktakes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BOM.inventorylocation')),
            ],
            options={
                'ordering': ['-conducted_date'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('receipt', 'Stock Receipt'), ('issue', 'Stock Issue'), ('adjustment', 'Stock Adjustment'), ('transfer', 'Stock Transfer'), ('allocation', 'Production Allocation'), ('deallocation', 'Production Deallocation')], max_length=20)),
                ('source_type', models.CharField(blank=True, choices=[('purchase', 'Purchase Order'), ('production', 'Production Order'), ('adjustment', 'Manual Adjustment'), ('transfer', 'Location Transfer'), ('bom', 'BOM Allocation')], max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='BOM.component')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BOM.inventorylocation')),
                ('related_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_transfers', to='BOM.inventorylocation')),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['component', 'created_date'], name='BOM_stocktr_compone_8c1e44_idx'), models.Index(fields=['source_type', 'source_reference'], name='BOM_stocktr_source__0446b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockTakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('counted_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('expected_unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BOM.component')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='BOM.stocktake')),
            ],
            options={
                'unique_together': {('stock_take', 'component')},
            },
        ),
        migrations.CreateModel(
            name='ReorderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('min_max', 'Min-Max'), ('reorder_point', 'Reorder Point'), ('periodic', 'Periodic Review')], default='min_max', max_length=20)),
                ('min_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('max_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reorder_point', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('order_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='BOM.component')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BOM.inventorylocation')),
            ],
            options={
                'unique_together': {('component', 'location')},
            },
        ),
    ]
