# Generated by Django 4.2.23 on 2025-08-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0013_stocktake_stocktransaction_stocktakeitem_reorderrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BOM.supplier'),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
