# Generated by Django 4.2.23 on 2025-08-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0014_bomitem_supplier_bomitem_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomitem',
            old_name='total_cost',
            new_name='cost',
        ),
    ]
