# Generated by Django 4.2.23 on 2025-08-28 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialPlan', '0002_alter_inventoryreservation_id_alter_materialplan_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BOM', '0015_rename_total_cost_bomitem_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.component'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BOM.inventorylocation'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='accepted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Accepted By'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialPlan.purchaserequisition', verbose_name='Requisition'),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.inventorylocation'),
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.component'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='BOM.component'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.inventorylocation'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='related_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_transfers', to='BOM.inventorylocation'),
        ),
    ]
