# Generated by Django 4.2.23 on 2025-08-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0016_alter_inventorytransaction_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentsupplier',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
