# Generated by Django 4.2.23 on 2025-08-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0017_componentsupplier_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentsupplier',
            name='price',
        ),
        migrations.AddField(
            model_name='bomitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
