# Generated by Django 4.2.23 on 2025-11-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0018_remove_componentsupplier_price_bomitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomheader',
            name='wastage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
