# Generated by Django 4.2.23 on 2025-11-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0019_bomheader_wastage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bomheader',
            old_name='wastage',
            new_name='consumables_value',
        ),
        migrations.AddField(
            model_name='bomheader',
            name='depreciation_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='electricity_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='maintenanance_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='overhaed_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='wastage_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
