# Generated by Django 4.2.23 on 2025-11-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0020_rename_wastage_bomheader_consumables_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomheader',
            name='total_material_cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
