# Generated by Django 4.2.23 on 2025-11-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0021_bomheader_total_material_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomheader',
            name='overall_cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
