# Generated by Django 4.2.23 on 2025-11-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0022_bomheader_overall_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomheader',
            name='consumables_value',
        ),
        migrations.RemoveField(
            model_name='bomheader',
            name='depreciation_value',
        ),
        migrations.RemoveField(
            model_name='bomheader',
            name='electricity_value',
        ),
        migrations.RemoveField(
            model_name='bomheader',
            name='maintenanance_value',
        ),
        migrations.RemoveField(
            model_name='bomheader',
            name='overhaed_value',
        ),
    ]
