# Generated by Django 4.2.23 on 2025-10-06 11:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MachinePlanning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=10, unique=True, verbose_name='Employee ID')),
                ('employee_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Hire Date')),
                ('contact_number', models.CharField(blank=True, max_length=15, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachinePlanning.workcenter', verbose_name='Primary Work Center')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employee_name'],
            },
        ),
        migrations.CreateModel(
            name='Proficeincy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Proficiency Name')),
                ('is_active', models.BooleanField(blank=True, verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_code', models.CharField(max_length=10, unique=True, verbose_name='Skill Code')),
                ('skill_name', models.CharField(max_length=50, verbose_name='Skill Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['skill_name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_code', models.CharField(max_length=10, unique=True, verbose_name='Shift Code')),
                ('shift_name', models.CharField(max_length=50, verbose_name='Shift Name')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('personal', 'Personal Leave'), ('bereavement', 'Bereavement Leave'), ('other', 'Other')], max_length=20, verbose_name='Leave Type')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('reason', models.TextField(verbose_name='Reason for Leave')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('notes', models.TextField(blank=True, verbose_name='Approver Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to='ManpowerPlan.employee', verbose_name='Approved By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='ManpowerPlan.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LaborAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Assignment Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Assignment Date')),
                ('hours_allocated', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(24)], verbose_name='Hours Allocated')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('absent', 'Absent'), ('reassigned', 'Reassigned')], default='planned', max_length=20, verbose_name='Assignment Status')),
                ('notes', models.TextField(blank=True, verbose_name='Assignment Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_assi_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_assignments', to='ManpowerPlan.employee', verbose_name='Assigned Employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_assignments', to='MachinePlanning.machinescheduling')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManpowerPlan.shift', verbose_name='Assigned Shift')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_assi_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Labor Assignment',
                'verbose_name_plural': 'Labor Assignments',
                'ordering': ['start_date', 'shift__start_time'],
            },
        ),
        migrations.CreateModel(
            name='LaborRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees_needed', models.PositiveSmallIntegerField(default=1, verbose_name='Employees Needed')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('min_proficiency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='require_proficiency', to='ManpowerPlan.proficeincy')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_requirements', to='MachinePlanning.routing')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MachinePlanning.machinescheduling')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManpowerPlan.skill', verbose_name='Required Skill')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Labor Requirement',
                'verbose_name_plural': 'Labor Requirements',
                'unique_together': {('routing', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_date', models.DateField(blank=True, null=True, verbose_name='Certification Date')),
                ('certified_by', models.CharField(blank=True, max_length=100, verbose_name='Certified By')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_skill_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='ManpowerPlan.employee')),
                ('proficiency', models.ForeignKey(blank=True, db_column='proficiency_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_proficiency', to='ManpowerPlan.proficeincy')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManpowerPlan.skill')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_skill_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Employee Skill',
                'verbose_name_plural': 'Employee Skills',
                'unique_together': {('employee', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Reason for Unavailability')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_avail_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='ManpowerPlan.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_avail_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Employee Availability',
                'verbose_name_plural': 'Employee Availabilities',
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('clock_in', models.DateTimeField(blank=True, null=True, verbose_name='Clock In Time')),
                ('clock_out', models.DateTimeField(blank=True, null=True, verbose_name='Clock Out Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late Arrival'), ('left_early', 'Left Early'), ('on_leave', 'On Leave')], default='present', max_length=20, verbose_name='Attendance Status')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Overtime Hours')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atten_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='ManpowerPlan.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManpowerPlan.shift', verbose_name='Shift')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atten_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
