# Generated by Django 4.2.23 on 2025-10-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlanning', '0011_remove_routing_component_remove_routing_created_by_and_more'),
        ('ManpowerPlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborrequirement',
            name='routing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_requirements', to='MachinePlanning.routingmaster'),
        ),
    ]
