# Generated by Django 4.2.23 on 2025-10-13 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManpowerPlan', '0002_alter_laborrequirement_routing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='is_active',
        ),
    ]
