# Generated by Django 4.2.23 on 2025-10-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManpowerPlan', '0003_remove_shift_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
