# Generated by Django 4.2.23 on 2025-10-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManpowerPlan', '0004_shift_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='break_time_end',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_time_start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
