# Generated by Django 4.2.23 on 2025-10-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManpowerPlan', '0005_shift_break_time_end_shift_break_time_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='break_time_end',
            new_name='break_time_period',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='break_time_start',
        ),
    ]
