# Generated by Django 4.2.23 on 2025-10-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManpowerPlan', '0006_rename_break_time_end_shift_break_time_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='break_time_period',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
