# Generated by Django 4.2.23 on 2025-10-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManpowerPlan', '0007_alter_shift_break_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='break_time_period',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
