# Generated by Django 4.2.23 on 2025-11-11 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MachinePlanning', '0063_remove_cogmaster_bom_header_and_more'),
        ('BOM', '0023_remove_bomheader_consumables_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('bom_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_cost_values', to='BOM.bomheader')),
            ],
            options={
                'verbose_name': 'Cost Element',
                'verbose_name_plural': 'Cost Element',
                'db_table': 'cost_element',
            },
        ),
        migrations.CreateModel(
            name='CostElementValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_values', to='COG.costelement')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_values_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_values_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cost Element Value',
                'verbose_name_plural': 'Cost Element Values',
                'db_table': 'cost_element_value',
            },
        ),
        migrations.CreateModel(
            name='COGMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_cost', models.CharField(max_length=10)),
                ('routing_cost', models.CharField(max_length=10)),
                ('total_prodcution_cost', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_cog_values', to='BOM.bomheader')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cog_values_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cog_values_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cog_master',
            },
        ),
        migrations.CreateModel(
            name='COGDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workstation', models.CharField(max_length=10)),
                ('machine', models.CharField(max_length=10)),
                ('employee', models.CharField(max_length=10)),
                ('machine_capacity', models.CharField(max_length=10)),
                ('employee_capacity', models.CharField(max_length=10)),
                ('machine_cost', models.CharField(max_length=10)),
                ('employee_cost', models.CharField(max_length=10)),
                ('avg_value', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cog_detail', to='COG.cogmaster')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cog_detail_created', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cog_operation', to='MachinePlanning.operation')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cog_detail_updated', to=settings.AUTH_USER_MODEL)),
                ('workcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cog_workcenter', to='MachinePlanning.workcenters')),
            ],
            options={
                'db_table': 'cog_detail',
            },
        ),
    ]
