# Generated by Django 4.2.23 on 2025-11-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cogmaster',
            name='other_cost',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
