# Generated by Django 4.2.7 on 2025-07-24 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0004_bomitem_position'),
        ('MachinePlan', '0002_alter_machinecapability_processing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinecapability',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.bomheader'),
        ),
        migrations.AlterField(
            model_name='machineschedule',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BOM.bomheader'),
        ),
    ]
