# Generated by Django 4.2.7 on 2025-07-25 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0008_alter_document_document_type'),
        ('MachinePlan', '0003_alter_machinecapability_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('RELEASED', 'Released'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_production_orders', to='BOM.bomheader', verbose_name='BOM Component')),
            ],
        ),
        migrations.CreateModel(
            name='MachinePlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BOM.bomheader', verbose_name='BOM Component')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MachinePlan.machine')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MachinePlan.operation')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.productionorder')),
            ],
            options={
                'verbose_name': 'BOM Machine Planning',
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('setup_time', models.PositiveIntegerField(help_text='Setup time in minutes')),
                ('run_time_per_unit', models.PositiveIntegerField(help_text='Run time per unit in minutes')),
                ('notes', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.bomheader', verbose_name='BOM Component')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.operation')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.workcenter')),
            ],
            options={
                'verbose_name': 'BOM Routing',
                'ordering': ['component', 'sequence'],
                'unique_together': {('component', 'sequence')},
            },
        ),
    ]
