# Generated by Django 4.2.7 on 2025-07-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0004_operation_workcenter_productionorder_machineplanning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinecapability',
            name='processing_time',
            field=models.DurationField(help_text='Time required to process one unit'),
        ),
        migrations.AlterField(
            model_name='machinecapability',
            name='setup_time',
            field=models.DurationField(help_text='Time required to setup machine for this component'),
        ),
    ]
