# Generated by Django 4.2.7 on 2025-07-28 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0005_alter_machinecapability_processing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.workcenter'),
        ),
    ]
