# Generated by Django 4.2.7 on 2025-07-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0006_machine_work_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='routing',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
