# Generated by Django 4.2.7 on 2025-07-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0007_routing_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routing',
            name='name',
        ),
    ]
