# Generated by Django 4.2.7 on 2025-07-30 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0008_remove_routing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='routing',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.productionorder'),
        ),
    ]
