# Generated by Django 4.2.7 on 2025-07-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0010_remove_machineschedule_component_and_more'),
        ('Manpower', '0002_alter_laborassignment_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineSchedule',
        ),
    ]
