# Generated by Django 4.2.23 on 2025-08-19 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialPlan', '0002_alter_inventoryreservation_id_alter_materialplan_id_and_more'),
        ('MachinePlan', '0012_machineplanning_routing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineplanning',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MaterialPlan.productionorder'),
        ),
        migrations.AlterField(
            model_name='machineplanning',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PLANNED', 'Planned')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='routing',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialPlan.productionorder'),
        ),
        migrations.DeleteModel(
            name='ProductionOrder',
        ),
    ]
