# Generated by Django 4.2.23 on 2025-08-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0013_alter_machineplanning_production_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineplanning',
            name='production_order',
        ),
        migrations.RemoveField(
            model_name='routing',
            name='production_order',
        ),
    ]
