# Generated by Django 4.2.23 on 2025-08-19 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialPlan', '0002_alter_inventoryreservation_id_alter_materialplan_id_and_more'),
        ('MachinePlan', '0014_remove_machineplanning_production_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineplanning',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialPlan.productionorder'),
        ),
        migrations.AddField(
            model_name='routing',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialPlan.productionorder'),
        ),
    ]
