# Generated by Django 4.2.23 on 2025-08-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0015_machineplanning_production_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routing',
            name='operation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
