# Generated by Django 4.2.23 on 2025-08-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0016_alter_routing_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routing',
            old_name='operation',
            new_name='operations',
        ),
    ]
