# Generated by Django 4.2.23 on 2025-08-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0017_rename_operation_routing_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcenter',
            name='is_routing',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
