# Generated by Django 4.2.23 on 2025-08-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0018_workcenter_is_routing'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcenter',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
