# Generated by Django 4.2.23 on 2025-08-20 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0019_workcenter_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineplanning',
            name='operation',
        ),
        migrations.AddField(
            model_name='machineplanning',
            name='workcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MachinePlan.workcenter'),
        ),
    ]
