# Generated by Django 4.2.23 on 2025-08-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0020_remove_machineplanning_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineplanning',
            name='machine',
            field=models.TextField(blank=True, null=True),
        ),
    ]
