# Generated by Django 4.2.23 on 2025-08-20 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0021_alter_machineplanning_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineplanning',
            name='workcenter',
        ),
        migrations.RemoveField(
            model_name='routing',
            name='operations',
        ),
        migrations.RemoveField(
            model_name='workcenter',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workcenter',
            name='is_routing',
        ),
        migrations.AddField(
            model_name='machineplanning',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MachinePlan.operation'),
        ),
        migrations.AddField(
            model_name='routing',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MachinePlan.operation'),
        ),
        migrations.AlterField(
            model_name='machineplanning',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MachinePlan.machine'),
        ),
    ]
