# Generated by Django 4.2.23 on 2025-08-20 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0012_alter_monthlycomponentdemand_options_and_more'),
        ('MaterialPlan', '0002_alter_inventoryreservation_id_alter_materialplan_id_and_more'),
        ('MachinePlan', '0022_remove_machineplanning_workcenter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BOM.bomheader', verbose_name='BOM Component')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MachinePlan.machine')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialPlan.productionorder')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MachinePlan.routing')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MachinePlan.workcenter')),
            ],
            options={
                'verbose_name': 'Machine Scheduling',
                'ordering': ['scheduled_start'],
            },
        ),
    ]
