# Generated by Django 4.2.23 on 2025-08-28 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0016_alter_inventorytransaction_component_and_more'),
        ('MachinePlan', '0023_machinescheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.machinetype'),
        ),
        migrations.AlterField(
            model_name='machineplanning',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.bomheader', verbose_name='BOM Component'),
        ),
        migrations.AlterField(
            model_name='machineplanning',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.machine'),
        ),
        migrations.AlterField(
            model_name='machineplanning',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.operation'),
        ),
        migrations.AlterField(
            model_name='machineplanning',
            name='routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.routing'),
        ),
        migrations.AlterField(
            model_name='machinescheduling',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.bomheader', verbose_name='BOM Component'),
        ),
        migrations.AlterField(
            model_name='machinescheduling',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.machine'),
        ),
        migrations.AlterField(
            model_name='machinescheduling',
            name='routing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.routing'),
        ),
        migrations.AlterField(
            model_name='machinescheduling',
            name='work_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.workcenter'),
        ),
        migrations.AlterField(
            model_name='routing',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.operation'),
        ),
    ]
