# Generated by Django 4.2.23 on 2025-09-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0024_alter_machine_machine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinescheduling',
            name='seq',
            field=models.TextField(blank=True, null=True),
        ),
    ]
