# Generated by Django 4.2.23 on 2025-09-11 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0012_alter_laborassignment_options_and_more'),
        ('MachinePlan', '0025_machinescheduling_seq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routing',
            options={'ordering': ['component', 'sequence'], 'verbose_name': 'BOM Routing', 'verbose_name_plural': 'BOM Routings'},
        ),
        migrations.AddField(
            model_name='routing',
            name='employees_needed',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='rou_Employees Needed'),
        ),
        migrations.AddField(
            model_name='routing',
            name='min_proficiency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rou_require_proficiency', to='Manpower.proficeincy'),
        ),
        migrations.AddField(
            model_name='routing',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routing',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manpower.skill', verbose_name='rou_Required Skill'),
        ),
        migrations.AlterField(
            model_name='routing',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Additional Notes'),
        ),
    ]
