# Generated by Django 4.2.23 on 2025-09-11 07:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0012_alter_laborassignment_options_and_more'),
        ('MachinePlan', '0026_alter_routing_options_routing_employees_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinescheduling',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manpower.employee', verbose_name='Assigned Employee'),
        ),
        migrations.AddField(
            model_name='machinescheduling',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Assignment Date'),
        ),
        migrations.AddField(
            model_name='machinescheduling',
            name='hours_allocated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(24)], verbose_name='Hours Allocated'),
        ),
        migrations.AddField(
            model_name='machinescheduling',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Schedule Name'),
        ),
        migrations.AddField(
            model_name='machinescheduling',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manpower.shift', verbose_name='Assigned Shift'),
        ),
        migrations.AddField(
            model_name='machinescheduling',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Assignment Date'),
        ),
        migrations.AlterField(
            model_name='machinescheduling',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Absent'), ('REASSIGNED', 'Reassigned')], default='SCHEDULED', max_length=20),
        ),
    ]
