# Generated by Django 4.2.23 on 2025-09-11 10:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialPlan', '0004_productionorder_order_status'),
        ('Manpower', '0012_alter_laborassignment_options_and_more'),
        ('BOM', '0018_remove_componentsupplier_price_bomitem_price'),
        ('MachinePlan', '0027_machinescheduling_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Schedule Name')),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.bomheader', verbose_name='BOM Component')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialPlan.productionorder')),
            ],
            options={
                'verbose_name': 'Machine Schedule',
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.RemoveField(
            model_name='machinescheduling',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='machinescheduling',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='machinescheduling',
            name='hours_allocated',
        ),
        migrations.RemoveField(
            model_name='machinescheduling',
            name='name',
        ),
        migrations.RemoveField(
            model_name='machinescheduling',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='machinescheduling',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='machinescheduling',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.CreateModel(
            name='MachineScheduleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.TextField(blank=True, null=True)),
                ('employee', models.TextField(blank=True, null=True, verbose_name='Assigned Employee')),
                ('hours_allocated', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.25), django.core.validators.MaxValueValidator(24)], verbose_name='Hours Allocated')),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ABSENT', 'Absent'), ('REASSIGNED', 'Reassigned')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.machine')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.routing')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='MachinePlan.machineschedule')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manpower.shift')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.workcenter')),
            ],
            options={
                'verbose_name': 'Machine Schedule Detail',
                'ordering': ['scheduled_start'],
            },
        ),
    ]
