# Generated by Django 4.2.23 on 2025-09-12 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0028_machineschedule_remove_machinescheduling_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineschedule',
            name='routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.routing'),
        ),
        migrations.AlterField(
            model_name='machinescheduledetail',
            name='employee',
            field=models.TextField(blank=True, null=True, verbose_name='Assign+ed Employee'),
        ),
    ]
