# Generated by Django 4.2.23 on 2025-09-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0029_machineschedule_routing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinescheduledetail',
            name='employee',
            field=models.TextField(blank=True, null=True, verbose_name='Assigned Employee'),
        ),
    ]
