# Generated by Django 4.2.23 on 2025-09-16 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manpower', '0012_alter_laborassignment_options_and_more'),
        ('MaterialPlan', '0004_productionorder_order_status'),
        ('BOM', '0018_remove_componentsupplier_price_bomitem_price'),
        ('MachinePlan', '0030_alter_machinescheduledetail_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.bomheader', verbose_name='BOM Component')),
            ],
            options={
                'verbose_name': 'BOM Routing',
                'verbose_name_plural': 'BOM Routings',
            },
        ),
        migrations.CreateModel(
            name='RoutingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('setup_time', models.PositiveIntegerField(help_text='Setup time in minutes')),
                ('run_time_per_unit', models.PositiveIntegerField(help_text='Run time per unit in minutes')),
                ('employees_needed', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Employees Needed')),
                ('min_proficiency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rout_require_proficiency', to='Manpower.proficeincy')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.operation')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MaterialPlan.productionorder')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='MachinePlan.routingmaster')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manpower.skill', verbose_name='Required Skill')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachinePlan.workcenter')),
            ],
            options={
                'verbose_name': 'Routing Detail',
                'verbose_name_plural': 'Routing Details',
                'ordering': ['routing', 'sequence'],
                'unique_together': {('routing', 'sequence')},
            },
        ),
    ]
