# Generated by Django 4.2.23 on 2025-09-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0031_routingmaster_routingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingmaster',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routingmaster',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
