# Generated by Django 4.2.23 on 2025-09-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0032_routingmaster_created_at_routingmaster_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingmaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
