# Generated by Django 4.2.23 on 2025-09-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0033_alter_routingmaster_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingdetail',
            name='run_time_per_unit',
            field=models.PositiveIntegerField(blank=True, help_text='Run time per unit in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='routingdetail',
            name='setup_time',
            field=models.PositiveIntegerField(blank=True, help_text='Setup time in minutes', null=True),
        ),
    ]
