# Generated by Django 4.2.23 on 2025-09-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0034_alter_routingdetail_run_time_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingdetail',
            name='employees_needed',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Employees Needed'),
        ),
    ]
