# Generated by Django 4.2.23 on 2025-09-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachinePlan', '0036_alter_routingmaster_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineschedule',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
    ]
