# Generated by Django 5.0.9 on 2025-07-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0024_client_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_module',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
