# Generated by Django 4.2.7 on 2025-07-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0025_alter_client_module_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow_matrix',
            name='form_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
