# Generated by Django 3.2.25 on 2025-07-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0025_alter_client_module_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='workflow_master',
            fields=[
                ('wf_id', models.AutoField(primary_key=True, serialize=False)),
                ('wf_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_master',
            },
        ),
    ]
