# Generated by Django 4.2.7 on 2025-07-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0026_alter_workflow_matrix_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow_details',
            name='primarykey',
            field=models.TextField(blank=True, null=True),
        ),
    ]
