# Generated by Django 4.2.7 on 2025-07-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0027_workflow_details_primarykey'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_workflow_details',
            name='primarykey',
            field=models.TextField(blank=True, null=True),
        ),
    ]
