# Generated by Django 4.2.7 on 2025-07-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0027_workflow_matrix_wf_id'),
        ('Workflow', '0028_history_workflow_details_primarykey'),
    ]

    operations = [
    ]
