# Generated by Django 4.2.7 on 2025-07-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0029_merge_20250717_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history_workflow_details',
            old_name='primarykey',
            new_name='primary_key',
        ),
        migrations.RenameField(
            model_name='workflow_details',
            old_name='primarykey',
            new_name='primary_key',
        ),
    ]
