# Generated by Django 4.2.7 on 2025-07-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workflow', '0030_rename_primarykey_history_workflow_details_primary_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_workflow_details',
            name='module',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow_details',
            name='module',
            field=models.TextField(blank=True, null=True),
        ),
    ]
