# Generated by Django 5.0.9 on 2025-07-24 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BOM', '0004_bomitem_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('sales_order_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('due_date', models.DateField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BOM.bomheader')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_material_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Plan',
                'verbose_name_plural': 'Material Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_available', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity_to_purchase', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity_to_produce', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity_reserved', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('required_date', models.DateField()),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reserved', 'Reserved'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BOM.component')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='MaterialPlan.materialplan')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BOM.supplier')),
            ],
            options={
                'verbose_name': 'Material Plan Item',
                'verbose_name_plural': 'Material Plan Items',
                'ordering': ['required_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BOM.inventory')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='MaterialPlan.materialplan')),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='MaterialPlan.materialplanitem')),
            ],
            options={
                'verbose_name': 'Inventory Reservation',
                'verbose_name_plural': 'Inventory Reservations',
            },
        ),
        migrations.CreateModel(
            name='MaterialShortageAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('available_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('required_date', models.DateField()),
                ('potential_delay_days', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.component')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='MaterialPlan.materialplan')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Shortage Alert',
                'verbose_name_plural': 'Material Shortage Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BOM.bomheader')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_production_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production Order',
                'verbose_name_plural': 'Production Orders',
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='materialplan',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MaterialPlan.productionorder'),
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('required_by_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BOM.component')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requisitions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requisitions', to='MaterialPlan.materialplan')),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='MaterialPlan.materialplanitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BOM.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Requisition',
                'verbose_name_plural': 'Purchase Requisitions',
                'ordering': ['-created_at'],
            },
        ),
    ]
