# Generated by Django 4.2.23 on 2025-08-28 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0016_alter_inventorytransaction_component_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MaterialPlan', '0002_alter_inventoryreservation_id_alter_materialplan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreservation',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.inventory'),
        ),
        migrations.AlterField(
            model_name='materialplan',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.bomheader'),
        ),
        migrations.AlterField(
            model_name='materialplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_material_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materialplanitem',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.component'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.bomheader'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_production_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.component'),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BOM.supplier'),
        ),
    ]
