# Generated by Django 4.2.23 on 2025-09-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PLM', '0002_statusaction_created_at_statusaction_created_by_and_more'),
        ('MaterialPlan', '0003_alter_inventoryreservation_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PLM.statusaction'),
        ),
    ]
