# Generated by Django 5.0.9 on 2025-08-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuManager', '0002_menumaster_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumaster',
            name='menu_action',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='menumaster',
            name='menu_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
