# Generated by Django 5.0.9 on 2025-07-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(blank=True, choices=[('Hindi', 'Hindi'), ('Bengali', 'Bengali'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Marathi', 'Marathi'), ('Gujarati', 'Gujarati'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam'), ('Punjabi', 'Punjabi'), ('Odia', 'Odia'), ('Assamese', 'Assamese'), ('Maithili', 'Maithili'), ('Santali', 'Santali'), ('Kashmiri', 'Kashmiri'), ('Nepali', 'Nepali'), ('Sindhi', 'Sindhi'), ('Konkani', 'Konkani'), ('Dogri', 'Dogri'), ('Manipuri', 'Manipuri'), ('Bhojpuri', 'Bhojpuri'), ('Urdu', 'Urdu'), ('English', 'English'), ('French', 'French'), ('German', 'German'), ('Spanish', 'Spanish'), ('Portuguese', 'Portuguese'), ('Russian', 'Russian'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Arabic', 'Arabic'), ('Bodo', 'Bodo'), ('Sanskrit', 'Sanskrit'), ('Mizo', 'Mizo'), ('Tulu', 'Tulu'), ('Khasi', 'Khasi'), ('Garo', 'Garo'), ('Nagamese', 'Nagamese'), ('Other', 'Other')], null=True)),
                ('isbn_no', models.TextField(blank=True, null=True, verbose_name='ISBN Number')),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('edition', models.TextField(blank=True, null=True)),
                ('publisher_name', models.TextField(blank=True, null=True, verbose_name='Publisher')),
                ('publisher_place', models.TextField(blank=True, null=True, verbose_name='Publisher Location')),
                ('year_of_publication', models.TextField(blank=True, null=True, verbose_name='Year')),
                ('accession_no', models.TextField(blank=True, null=True, verbose_name='Accession Number')),
                ('class_no', models.TextField(blank=True, null=True, verbose_name='Class Number')),
                ('book_no', models.TextField(blank=True, null=True, verbose_name='Book Number')),
                ('pagination', models.TextField(blank=True, null=True, verbose_name='Pages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_auto_generated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Book Metadata',
                'verbose_name_plural': 'Books Metadata',
                'ordering': ['-created_at'],
            },
        ),
    ]
