# Generated by Django 5.0.9 on 2025-09-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesPurchase', '0002_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('JPY', 'JPY - Japanese Yen'), ('CAD', 'CAD - Canadian Dollar'), ('AUD', 'AUD - Australian Dollar'), ('CHF', 'CHF - Swiss Franc'), ('CNY', 'CNY - Chinese Yuan'), ('INR', 'INR - Indian Rupee'), ('SGD', 'SGD - Singapore Dollar'), ('AED', 'AED - UAE Dirham'), ('SAR', 'SAR - Saudi Riyal')], default='USD', max_length=3),
        ),
    ]
