# Generated by Django 5.0.9 on 2025-09-07 15:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0018_remove_componentsupplier_price_bomitem_price'),
        ('SalesPurchase', '0005_alter_salesorder_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('part', 'Part'), ('product', 'Product')], max_length=20)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BOM.bomheader')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BOM.component')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='SalesPurchase.invoice')),
                ('sales_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SalesPurchase.salesorderitem')),
            ],
        ),
    ]
