# Generated by Django 5.0.9 on 2025-09-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesPurchase', '0007_alter_quotation_subtotal_alter_quotation_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
    ]
