# Generated by Django 5.0.9 on 2025-09-15 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0018_remove_componentsupplier_price_bomitem_price'),
        ('SalesPurchase', '0012_alter_customerpricing_bom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpricing',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BOM.bomheader'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BOM.bomheader'),
        ),
        migrations.AlterField(
            model_name='rfqitem',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BOM.bomheader'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BOM.bomheader'),
        ),
    ]
