# Generated by Django 5.0.9 on 2025-09-16 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOM', '0018_remove_componentsupplier_price_bomitem_price'),
        ('SalesPurchase', '0013_alter_customerpricing_bom_alter_quotationitem_bom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_VAI',
            fields=[
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Invoice',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.AlterField(
            model_name='customerpricing',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BOM.bomheader'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BOM.bomheader'),
        ),
        migrations.AlterField(
            model_name='rfqitem',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BOM.bomheader'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BOM.bomheader'),
        ),
        migrations.CreateModel(
            name='InvoiceItem_VAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='SalesPurchase.invoice')),
            ],
        ),
    ]
