# Generated by Django 5.0.9 on 2025-09-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesPurchase', '0014_invoice_vai_alter_customerpricing_bom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_vai',
            name='customer_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_vai',
            name='due_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_vai',
            name='invoice_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_vai',
            name='invoice_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice_vai',
            name='invoice_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_vai',
            name='status',
            field=models.TextField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice_vai',
            name='total_amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_vai',
            name='vendor_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem_vai',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem_vai',
            name='price_per_unit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem_vai',
            name='quantity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem_vai',
            name='total',
            field=models.TextField(blank=True, null=True),
        ),
    ]
