# Generated by Django 5.0.9 on 2025-09-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesPurchase', '0015_alter_invoice_vai_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem_vai',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='SalesPurchase.invoice_vai'),
        ),
    ]
