# Generated by Django 5.0.9 on 2025-09-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesPurchase', '0016_alter_invoiceitem_vai_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice_vai',
            options={},
        ),
        migrations.AlterModelTable(
            name='invoice_vai',
            table=None,
        ),
    ]
